### ISSUE TITLE
URL outdated

### ISSUE THREAD

**Issue by subnut** [ejmastnak/ejmastnak.github.io#1]
This URL has changed -
https://github.com/ejmastnak/ejmastnak.github.io/blob/738dae359629294c2d709269f07b6ccdd76d22f4/tutorials/vim-latex/intro.md?plain=1#L77

```diff
-https://castel.dev/post/lecture-notes0/
+https://castel.dev/post/lecture-notes-1/
```

**Comment by ejmastnak** [comment]
Thank you for catching this! Fixed.
